server:
  port: 8081

spring:
  application:
    name: user-service

# Example DB config (we’ll wire later)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Atharva03@#
